FROM mdagost/pug_classifier_notebook
MAINTAINER mdagost@gmail.com

RUN pip install flask

COPY flask_scoring_api.py /home/ubuntu/flask_scoring_api.py

EXPOSE 5000
CMD python /home/ubuntu/flask_scoring_api.py